class LocationModel {
  final String? id;
  final String? areaId;
  final String areaName;
  final String? postCode;
  // These fields are needed for adding, but might not be in the GET response based on your JSON
  final String? city;
  final String? state;
  final String? geoBoundary; 

  LocationModel({
    this.id,
    this.areaId,
    required this.areaName,
    this.postCode,
    this.city,
    this.state,
    this.geoBoundary,
  });

  factory LocationModel.fromJson(Map<String, dynamic> json) {
    return LocationModel(
      id: json['id'],
      areaId: json['areaId'],
      areaName: json['areaName'] ?? '',
      postCode: json['postCode'],
      // Add other fields if the GET api returns them later
    );
  }

  Map<String, dynamic> toJson() {
    return {
      "areaId": areaId, // Usually generated by backend or UUID on front
      "areaName": areaName,
      "geoPolygonType": "Polygon", // Hardcoded as per requirement
      "geoBoundary": geoBoundary,
      "city": city,
      "state": state,
      "postCode": postCode,
    };
  }
}